### ISSUE TITLE
how to attach a custom callback to a route

### ISSUE THREAD

**Issue by araker** [ergo/crossroadsjs-router#2]
According to the readme there is a additional per-route custom callback support when an url is matched or not found. 

Though when looking at line [188](https://github.com/ergo/crossroadsjs-router/blob/master/crossroadsjs-behavior.html#L188) of crossroadsjs-behavior.html I see that undefined is used for the callback argument of addRoute. Is there another way to add a callback per route?

**Comment by ergo** [comment]
I'm not sure if we can add crossroad-callbacks there because there is no easy way to pass functions there, however what i meant was that `crossroadsjs-matched` event is fired - so you can subscribe to that and act upon its changes.

**Comment by araker** [comment]
Thanks for the fast reply, listening to the event did the trick.
